remove unused useradd
Error: buildx failed with: error: failed to solve: process "/bin/sh -c useradd appuser && chown -R appuser /app" did not complete successfully: exit code: 127